---
title: "Meta report"
output: html_document
date: "2025-04-22"
params:
  results_file: !r here::here("results", "results_rmarkdown.RData")
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
env <- new.env()
load(params$results_file, envir = env)
```

## Results {.tabset}

```{r results="asis"}
env$results |> 
  purrr::walk(
    function(x) {
      cat(paste0("### ", glue::glue("p: {x$params$prop} f: {x$params$folds} s: {x$params$seed}"), "\n"))
      
      cat("\n")
      
      cat("```r\n")
      print(x$params)
      
      cat("```\n")
      
      (x$p_values |>
        dplyr::mutate(
          max_significant = p_value == max(p_value[p_value <= 0.05]),
          label = dplyr::if_else(max_significant, glue::glue("y = {cdf} / p_value = {round(p_value, 5)}"), NA_character_),
          yintercept = dplyr::if_else(max_significant, cdf, NA),
        ) |>
        ggplot2::ggplot(ggplot2::aes(x = p_value, y = cdf, label = label)) +
          ggplot2::geom_line(color = "blue") +
          ggplot2::geom_ribbon(ggplot2::aes(ymin = 0, ymax = cdf), alpha = 0.1) +
          ggplot2::geom_vline(xintercept = 0.05, linetype = "dashed", color = "red") +
          ggplot2::geom_hline(ggplot2::aes(yintercept = yintercept), na.rm = TRUE, linetype = "dashed", color = "gray") +
          ggplot2::geom_label(nudge_x = .05, nudge_y = -.05, hjust = 0, na.rm = TRUE, fill = "white") +
          ggplot2::labs(title = "Cumulative Distribution of p-values",
               x = "p-value",
               y = "Empirical CDF") +
          ggplot2::expand_limits(x = c(0, 1), y = c(0, 1)) +
          ggplot2::theme_minimal()) |> 
        print()
      
      cat("\n\n")
    }
  )

```


